# Generated by Django 3.0.8 on 2020-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='features',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='releases',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
