# Generated by Django 3.0.8 on 2020-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200719_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
