# Generated by Django 3.0.8 on 2020-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_signup_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to='videos')),
            ],
        ),
    ]
