# Generated by Django 3.0.8 on 2020-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200720_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='image',
        ),
        migrations.RemoveField(
            model_name='features',
            name='image',
        ),
        migrations.RemoveField(
            model_name='releases',
            name='image',
        ),
        migrations.AddField(
            model_name='discover',
            name='video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='features',
            name='video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releases',
            name='video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
