# Generated by Django 3.0.8 on 2020-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200720_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='video',
        ),
        migrations.RemoveField(
            model_name='features',
            name='video',
        ),
        migrations.RemoveField(
            model_name='releases',
            name='video',
        ),
        migrations.AddField(
            model_name='discover',
            name='image',
            field=models.ImageField(blank=True, upload_to='discover'),
        ),
        migrations.AddField(
            model_name='features',
            name='image',
            field=models.ImageField(blank=True, upload_to='features'),
        ),
        migrations.AddField(
            model_name='releases',
            name='image',
            field=models.ImageField(blank=True, upload_to='releases'),
        ),
    ]
