# Generated by Django 3.0.8 on 2020-07-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200720_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
