# Generated by Django 3.0.8 on 2020-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200720_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover',
            name='video',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='features',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
