# Generated by Django 3.0.8 on 2020-07-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200720_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='secret_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
