# Generated by Django 3.0.8 on 2020-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_signup_secret_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
