# Generated by Django 3.0.8 on 2020-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ads_ad3'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='videoo',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='ad3',
        ),
    ]
